// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SubastaYa.Infraestructura.Persistencia;

#nullable disable

namespace SubastaYa.Infraestructura.Migraciones
{
    [DbContext(typeof(SubastaYaDbContext))]
    [Migration("20260907030111_AdicionGanadorYMontoFinalSubasta")]
    partial class AdicionGanadorYMontoFinalSubasta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SubastaYa.Dominio.Entidades.Billetera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("SaldoDisponible")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoRetenido")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Billeteras", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RowVersion = new byte[0],
                            SaldoDisponible = 0m,
                            SaldoRetenido = 0m,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            RowVersion = new byte[0],
                            SaldoDisponible = 5000m,
                            SaldoRetenido = 0m,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 3,
                            RowVersion = new byte[0],
                            SaldoDisponible = 10000m,
                            SaldoRetenido = 3500m,
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 4,
                            RowVersion = new byte[0],
                            SaldoDisponible = 200m,
                            SaldoRetenido = 0m,
                            UsuarioId = 4
                        },
                        new
                        {
                            Id = 5,
                            RowVersion = new byte[0],
                            SaldoDisponible = 50000m,
                            SaldoRetenido = 1500m,
                            UsuarioId = 5
                        });
                });

            modelBuilder.Entity("SubastaYa.Dominio.Entidades.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Categorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Dispositivos y gadgets electrónicos",
                            Nombre = "Electrónica"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Artículos para el hogar y decoración",
                            Nombre = "Hogar"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Equipamiento y artículos deportivos",
                            Nombre = "Deportes"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Obras de arte, pinturas y esculturas",
                            Nombre = "Arte"
                        });
                });

            modelBuilder.Entity("SubastaYa.Dominio.Entidades.MovimientoContable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BilleteraId")
                        .HasColumnType("int");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("BilleteraId");

                    b.ToTable("MovimientosContables", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BilleteraId = 3,
                            Concepto = "Carga inicial de saldo",
                            FechaMovimiento = new DateTime(2026, 8, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            Monto = 15000m,
                            Tipo = "Carga"
                        },
                        new
                        {
                            Id = 2,
                            BilleteraId = 3,
                            Concepto = "Retención por pujas activas en subastas",
                            FechaMovimiento = new DateTime(2026, 8, 29, 12, 0, 0, 0, DateTimeKind.Utc),
                            Monto = -3500m,
                            Tipo = "Retencion"
                        },
                        new
                        {
                            Id = 3,
                            BilleteraId = 5,
                            Concepto = "Carga inicial de saldo",
                            FechaMovimiento = new DateTime(2026, 8, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            Monto = 55000m,
                            Tipo = "Carga"
                        },
                        new
                        {
                            Id = 4,
                            BilleteraId = 5,
                            Concepto = "Retención por puja en subasta Cuadro Óleo",
                            FechaMovimiento = new DateTime(2026, 8, 30, 10, 0, 0, 0, DateTimeKind.Utc),
                            Monto = -1500m,
                            Tipo = "Retencion"
                        },
                        new
                        {
                            Id = 5,
                            BilleteraId = 4,
                            Concepto = "Carga inicial de saldo",
                            FechaMovimiento = new DateTime(2026, 8, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            Monto = 200m,
                            Tipo = "Carga"
                        },
                        new
                        {
                            Id = 6,
                            BilleteraId = 2,
                            Concepto = "Carga inicial de saldo vendedor",
                            FechaMovimiento = new DateTime(2026, 8, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            Monto = 5000m,
                            Tipo = "Carga"
                        });
                });

            modelBuilder.Entity("SubastaYa.Dominio.Entidades.Puja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaPuja")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PostorId")
                        .HasColumnType("int");

                    b.Property<int>("SubastaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostorId");

                    b.HasIndex("SubastaId");

                    b.ToTable("Pujas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaPuja = new DateTime(2026, 8, 29, 12, 0, 0, 0, DateTimeKind.Utc),
                            Monto = 5500m,
                            PostorId = 3,
                            SubastaId = 1
                        },
                        new
                        {
                            Id = 2,
                            FechaPuja = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Monto = 6000m,
                            PostorId = 5,
                            SubastaId = 1
                        },
                        new
                        {
                            Id = 3,
                            FechaPuja = new DateTime(2026, 8, 30, 10, 0, 0, 0, DateTimeKind.Utc),
                            Monto = 8500m,
                            PostorId = 3,
                            SubastaId = 2
                        },
                        new
                        {
                            Id = 4,
                            FechaPuja = new DateTime(2026, 8, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            Monto = 4500m,
                            PostorId = 5,
                            SubastaId = 4
                        });
                });

            modelBuilder.Entity("SubastaYa.Dominio.Entidades.Subasta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GanadorId")
                        .HasColumnType("int");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("IncrementoMinimo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MontoFinal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioActual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioInicial")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("VendedorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("GanadorId");

                    b.HasIndex("VendedorId");

                    b.ToTable("Subastas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Descripcion = "Notebook gamer MSI con RTX 4060, 16GB RAM, 512GB SSD. Estado impecable.",
                            Estado = "Activa",
                            FechaFin = new DateTime(2026, 9, 4, 12, 0, 0, 0, DateTimeKind.Utc),
                            FechaInicio = new DateTime(2026, 8, 28, 12, 0, 0, 0, DateTimeKind.Utc),
                            ImagenUrl = "https://images.unsplash.com/photo-1603302576837-37561b2e2302",
                            IncrementoMinimo = 100m,
                            PrecioActual = 6000m,
                            PrecioInicial = 5000m,
                            Titulo = "Notebook Gamer MSI",
                            VendedorId = 2
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 4,
                            Descripcion = "Cuadro al óleo original de artista emergente. Técnica mixta sobre lienzo 80x60.",
                            Estado = "Activa",
                            FechaFin = new DateTime(2026, 8, 30, 12, 30, 0, 0, DateTimeKind.Utc),
                            FechaInicio = new DateTime(2026, 8, 27, 12, 0, 0, 0, DateTimeKind.Utc),
                            ImagenUrl = "https://images.unsplash.com/photo-1579783902614-a3fb3927b675",
                            IncrementoMinimo = 200m,
                            PrecioActual = 8500m,
                            PrecioInicial = 8000m,
                            Titulo = "Cuadro Óleo Original",
                            VendedorId = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 3,
                            Descripcion = "Bicicleta de montaña rodado 29, cuadro de aluminio, 21 velocidades.",
                            Estado = "Pendiente",
                            FechaFin = new DateTime(2026, 9, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            FechaInicio = new DateTime(2026, 9, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            ImagenUrl = "https://images.unsplash.com/photo-1485965120184-e220f721d03e",
                            IncrementoMinimo = 50m,
                            PrecioActual = 3000m,
                            PrecioInicial = 3000m,
                            Titulo = "Bicicleta Montaña R29",
                            VendedorId = 2
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 1,
                            Descripcion = "Smart TV LED 55 pulgadas 4K UHD con sistema operativo integrado.",
                            Estado = "Finalizada",
                            FechaFin = new DateTime(2026, 8, 27, 12, 0, 0, 0, DateTimeKind.Utc),
                            FechaInicio = new DateTime(2026, 8, 20, 12, 0, 0, 0, DateTimeKind.Utc),
                            GanadorId = 5,
                            ImagenUrl = "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1",
                            IncrementoMinimo = 100m,
                            MontoFinal = 4500m,
                            PrecioActual = 4500m,
                            PrecioInicial = 4000m,
                            Titulo = "Smart TV 55 Pulgadas",
                            VendedorId = 2
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 2,
                            Descripcion = "Set de 5 sartenes profesionales con revestimiento cerámico antiadherente.",
                            Estado = "Desierta",
                            FechaFin = new DateTime(2026, 8, 28, 12, 0, 0, 0, DateTimeKind.Utc),
                            FechaInicio = new DateTime(2026, 8, 20, 12, 0, 0, 0, DateTimeKind.Utc),
                            ImagenUrl = "https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7",
                            IncrementoMinimo = 50m,
                            PrecioActual = 1500m,
                            PrecioInicial = 1500m,
                            Titulo = "Set de Sartenes Profesional",
                            VendedorId = 2
                        });
                });

            modelBuilder.Entity("SubastaYa.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClaveHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Alias")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alias = "admin",
                            ClaveHash = "PrP+ZrMeO00Q+nC1ytSccRIpSvauTkdqHEBRVdRaoSE=",
                            Email = "admin@subastaya.com",
                            FechaRegistro = new DateTime(2026, 7, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Rol = "Administrador",
                            Version = new byte[0]
                        },
                        new
                        {
                            Id = 2,
                            Alias = "juan_vendedor",
                            ClaveHash = "NhyFoVwMoMd3D6nVNXH2gDqgcOXdVgcgL2tAAMWo64g=",
                            Email = "juan@mail.com",
                            FechaRegistro = new DateTime(2026, 8, 5, 12, 0, 0, 0, DateTimeKind.Utc),
                            Rol = "Vendedor",
                            Version = new byte[0]
                        },
                        new
                        {
                            Id = 3,
                            Alias = "maria_compradora",
                            ClaveHash = "0TgymXq9YMECHsRDfhFEykEpOXQUGo68Feu0Wj4onnE=",
                            Email = "maria@mail.com",
                            FechaRegistro = new DateTime(2026, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Rol = "Comprador",
                            Version = new byte[0]
                        },
                        new
                        {
                            Id = 4,
                            Alias = "pedro_postor",
                            ClaveHash = "4SFWNm2mTLNbFQO59OhfFMdd4iQezexdyvD6hDW/2tE=",
                            Email = "pedro@mail.com",
                            FechaRegistro = new DateTime(2026, 8, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            Rol = "Comprador",
                            Version = new byte[0]
                        },
                        new
                        {
                            Id = 5,
                            Alias = "ana_vip",
                            ClaveHash = "fPHusZzQGjLTGP9VJejilp/m1XXfEdAsAgbpKgU7GY8=",
                            Email = "ana@mail.com",
                            FechaRegistro = new DateTime(2026, 8, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            Rol = "Comprador",
                            Version = new byte[0]
                        });
                });

            modelBuilder.Entity("SubastaYa.Dominio.Entidades.Billetera", b =>
                {
                    b.HasOne("SubastaYa.Dominio.Entidades.Usuario", "Usuario")
                        .WithOne("Billetera")
                        .HasForeignKey("SubastaYa.Dominio.Entidades.Billetera", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SubastaYa.Dominio.Entidades.MovimientoContable", b =>
                {
                    b.HasOne("SubastaYa.Dominio.Entidades.Billetera", "Billetera")
                        .WithMany("Movimientos")
                        .HasForeignKey("BilleteraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Billetera");
                });

            modelBuilder.Entity("SubastaYa.Dominio.Entidades.Puja", b =>
                {
                    b.HasOne("SubastaYa.Dominio.Entidades.Usuario", "Postor")
                        .WithMany("Pujas")
                        .HasForeignKey("PostorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaYa.Dominio.Entidades.Subasta", "Subasta")
                        .WithMany("Pujas")
                        .HasForeignKey("SubastaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Postor");

                    b.Navigation("Subasta");
                });

            modelBuilder.Entity("SubastaYa.Dominio.Entidades.Subasta", b =>
                {
                    b.HasOne("SubastaYa.Dominio.Entidades.Categoria", "Categoria")
                        .WithMany("Subastas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaYa.Dominio.Entidades.Usuario", "Ganador")
                        .WithMany()
                        .HasForeignKey("GanadorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SubastaYa.Dominio.Entidades.Usuario", "Vendedor")
                        .WithMany("SubastasComoVendedor")
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Ganador");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("SubastaYa.Dominio.Entidades.Billetera", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("SubastaYa.Dominio.Entidades.Categoria", b =>
                {
                    b.Navigation("Subastas");
                });

            modelBuilder.Entity("SubastaYa.Dominio.Entidades.Subasta", b =>
                {
                    b.Navigation("Pujas");
                });

            modelBuilder.Entity("SubastaYa.Dominio.Entidades.Usuario", b =>
                {
                    b.Navigation("Billetera");

                    b.Navigation("Pujas");

                    b.Navigation("SubastasComoVendedor");
                });
#pragma warning restore 612, 618
        }
    }
}
