/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActividadRouteImport } from './routes/actividad'
import { Route as BilleteraRouteImport } from './routes/billetera'
import { Route as PublicarRouteImport } from './routes/publicar'
import { Route as SubastaIdRouteImport } from './routes/subasta.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActividadRoute = ActividadRouteImport.update({
  id: '/actividad',
  path: '/actividad',
  getParentRoute: () => rootRouteImport,
} as any)
const BilleteraRoute = BilleteraRouteImport.update({
  id: '/billetera',
  path: '/billetera',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicarRoute = PublicarRouteImport.update({
  id: '/publicar',
  path: '/publicar',
  getParentRoute: () => rootRouteImport,
} as any)
const SubastaIdRoute = SubastaIdRouteImport.update({
  id: '/subasta/$id',
  path: '/subasta/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actividad': typeof ActividadRoute
  '/billetera': typeof BilleteraRoute
  '/publicar': typeof PublicarRoute
  '/subasta/$id': typeof SubastaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actividad': typeof ActividadRoute
  '/billetera': typeof BilleteraRoute
  '/publicar': typeof PublicarRoute
  '/subasta/$id': typeof SubastaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actividad': typeof ActividadRoute
  '/billetera': typeof BilleteraRoute
  '/publicar': typeof PublicarRoute
  '/subasta/$id': typeof SubastaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/actividad' | '/billetera' | '/publicar' | '/subasta/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/actividad' | '/billetera' | '/publicar' | '/subasta/$id'
  id:
    | '__root__'
    | '/'
    | '/actividad'
    | '/billetera'
    | '/publicar'
    | '/subasta/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActividadRoute: typeof ActividadRoute
  BilleteraRoute: typeof BilleteraRoute
  PublicarRoute: typeof PublicarRoute
  SubastaIdRoute: typeof SubastaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actividad': {
      id: '/actividad'
      path: '/actividad'
      fullPath: '/actividad'
      preLoaderRoute: typeof ActividadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billetera': {
      id: '/billetera'
      path: '/billetera'
      fullPath: '/billetera'
      preLoaderRoute: typeof BilleteraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicar': {
      id: '/publicar'
      path: '/publicar'
      fullPath: '/publicar'
      preLoaderRoute: typeof PublicarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subasta/$id': {
      id: '/subasta/$id'
      path: '/subasta/$id'
      fullPath: '/subasta/$id'
      preLoaderRoute: typeof SubastaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActividadRoute: ActividadRoute,
  BilleteraRoute: BilleteraRoute,
  PublicarRoute: PublicarRoute,
  SubastaIdRoute: SubastaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
